<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Zend Skeleton Light')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    </head>

    <body>
        <header></header>

        <div role="main">
            <?php echo $this->content; ?>
        </div>

        <footer></footer>

        <?php echo $this->inlineScript(); ?>
    </body>
</html>
